---
title: "Open Research Survey Report"
author: "Emma Wilson"
date: "22/02/2021"
output: 
    html_document:
      theme: cosmo
---

```{r select, include=FALSE}
# Choose the data to run the report on
choose <- c("all", "mrc", "uob", "babraham")[1]
```

```{r logo, echo=FALSE}
htmltools::img(src = knitr::image_uri(file.path("logo.jpg")), 
               alt = 'UKRN logo', 
               style = 'position:absolute; top:0; right:0; padding:25px 250px;')
```

---

```{r setup, include=FALSE}
# R packages
library(grid)         # Plot arrangement
library(gridExtra)    # Plot arrangement
library(tidyverse)    # Tivdyverse packages
# Functions
source("functions/format_distribution.R") # Create a histogram of responses
source("functions/format_leadership.R")   # Format MajorleadershipRole for graph
source("functions/format_priority.R")     # Format OR area priority responses
source("functions/format_training.R")     # Format training responses for graph
source("functions/read_survey.R")         # Read in and format survey data
# KnitR
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r data, include=FALSE}
# Clean column text
col_order <- read_csv("data-helpers/colOrder.csv")
# MRC taxonomy
mrc_group <- read_csv("data-helpers/mrcTaxonomy.csv")

# Read in survey data
dat_mrc <- read_survey("data", "MRC") # MRC-funded institutions
dat_uob <- read_survey("data", "UoB") # University of Bristol
dat_bab <- read_survey("data", "Babraham") # Babraham Institute
# Bind into one dataframe
dat <- rbind(dat_mrc, dat_uob, dat_bab)

# Clear environment
rm(col_order, dat_bab, dat_mrc, dat_uob, mrc_group)

# Select relevant data
if(choose == "all"){
  dat <- dat
} else if(choose == "mrc"){
  dat <- filter(dat, Unit == "MRC")
} else if(choose == "uob"){
  dat <- filter(dat, Unit == "UoB")
} else if(choose == "babraham"){
  dat <- filter(dat, Unit == "Babraham")
}

# Format MajorLeadership Role Column
dat <- format_leadership(dat)
```

# Aim
<!-- add aim of survey -->

# Survey Data

```{r, echo=FALSE, results='asis'}
p1 <- ggplot(dat, aes(x = factor(Unit))) +
  geom_bar(aes(fill = Discipline)) +
  scale_fill_manual(values = c("#28295B", "#4E4F86", "#9e9e9e")) +
  ylim(0, nrow(dat)) +
  theme(legend.position="right", legend.text = element_text(size = 7)) +
  xlab("Organisation") + ylab("Number of Responses") +
  theme(plot.title = element_text(hjust = 0.5))

p2 <- count(dat, Leadership) %>%
  ggplot(aes(x = Leadership, y = n)) +
  geom_bar(fill = "#13A89E", stat = "identity") +
  ylim(0, nrow(dat)) +
  xlab("Leadership role") + ylab("Number of Responses") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
  theme(plot.title = element_text(hjust = 0.5))

if(choose == "all"){
  # Number of responses text
  cat('This report summarises', nrow(dat), 'survey responses from life and health sciences researchers at Medical Research Council (MRC)-funded institutions, The University of Bristol, and The Babraham Institute. \n\n')
  # Plots
  grid.arrange(p1, p2, nrow = 1, widths = c(3, 2))
} else if(choose == "mrc"){
  # Number of responses text
  cat('This report summarises', nrow(dat), 'survey responses from life and health sciences researchers at Medical Research Council (MRC)-funded institutions. \n\n')
  # Plots
  grid.arrange(p1, p2, nrow = 1, widths = c(3, 2))
} else if(choose == "uob"){
  # Number of responses text
  cat('This report summarises', nrow(dat), 'survey responses from life and health sciences researchers at The University of Bristol.')
  # Plot
  grid.arrange(p2, nrow = 1, widths = c(2))
} else if(choose == "babraham"){
  # Number of responses text
  cat('This report summarises', nrow(dat), 'survey responses from life sciences researchers at The Babraham Institute.')
  # Plot
  grid.arrange(p2, nrow = 1, widths = c(2))
} else {
  cat('Error: Please choose a valid data breakdown.')
}
```

# Open Research Training

```{r training, include=FALSE}
# Subset and format responses from those who want training
dat_training <- format_training(dat, training = "Yes")

# Subset and format responses from those who do not indicate they want training
dat_no_training <- format_training(dat, training = "No")
```

```{r training-plot, echo=FALSE}
ggplot(dat_training, aes(x = factor(OR_Area))) +
  geom_bar(aes(fill = Response)) +
  scale_fill_manual(values = c("#28295B", "#4E4F86", "#13A89E", "#9e9e9e")) +
  ylim(0, nrow(dat)) +
  theme(legend.position="bottom", legend.text = element_text(size = 7)) +
  xlab("Open Research Area") + ylab("Number of Responses") +
  theme(plot.title = element_text(hjust = 0.5))

ggplot(dat_no_training, aes(x = factor(OR_Area))) +
  geom_bar(aes(fill = Response)) +
  scale_fill_manual(values = c("#28295B", "#4E4F86", "#13A89E", "#EC008C")) +
  ylim(0, nrow(dat)) +
  theme(legend.position="bottom", legend.text = element_text(size = 6)) +
  xlab("OR Area") + ylab("Number of Responses") +
  theme(plot.title = element_text(hjust = 0.5))
```

# Priority of Training Topics

```{r priority, include=FALSE}
priority_main <- format_priority(dat)
```

```{r priority-plot, echo=FALSE}
ggplot(priority_main, aes(x = priority_areas, y = priority_count)) +
  geom_col(aes(fill = priority_rank)) +
  scale_fill_manual(values = c("#28295B", "#4E4F86", "#13A89E", "#ed68b7", "#EC008C", "#9e9e9e")) +
  theme(legend.position="bottom") +
  ggtitle("All Organisations") + xlab("OR Areas") + ylab("Number of Respondents") +
  theme(plot.title = element_text(hjust = 0.5))
```

